// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGXoV5hKf6QIFSldjB2eAdmnIym7Z3Cpc',
    appId: '1:417803462333:web:fb7e6585c1eab7d1cef9d4',
    messagingSenderId: '417803462333',
    projectId: 'vocagacha-8e17c',
    authDomain: 'vocagacha-8e17c.firebaseapp.com',
    storageBucket: 'vocagacha-8e17c.firebasestorage.app',
    measurementId: 'G-86Z8P96QQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-3sUg0DTTYJlL0w9mAiwg9O2wWl2681c',
    appId: '1:417803462333:android:5a3de1ccc37f7d1acef9d4',
    messagingSenderId: '417803462333',
    projectId: 'vocagacha-8e17c',
    storageBucket: 'vocagacha-8e17c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ99yTwdWGdQQAQQDNKZmnEVOOZ7as4BQ',
    appId: '1:417803462333:ios:da2e098f87336863cef9d4',
    messagingSenderId: '417803462333',
    projectId: 'vocagacha-8e17c',
    storageBucket: 'vocagacha-8e17c.firebasestorage.app',
    iosBundleId: 'com.example.vocagacha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ99yTwdWGdQQAQQDNKZmnEVOOZ7as4BQ',
    appId: '1:417803462333:ios:da2e098f87336863cef9d4',
    messagingSenderId: '417803462333',
    projectId: 'vocagacha-8e17c',
    storageBucket: 'vocagacha-8e17c.firebasestorage.app',
    iosBundleId: 'com.example.vocagacha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGXoV5hKf6QIFSldjB2eAdmnIym7Z3Cpc',
    appId: '1:417803462333:web:04667c7281f8ce4bcef9d4',
    messagingSenderId: '417803462333',
    projectId: 'vocagacha-8e17c',
    authDomain: 'vocagacha-8e17c.firebaseapp.com',
    storageBucket: 'vocagacha-8e17c.firebasestorage.app',
    measurementId: 'G-CPNR9WLX2Y',
  );
}
